/*
 *  Created on: May 27, 2013
 *      Author: Mirko Myllykoski (mirko.myllykoski@gmail.com)
 */

#ifndef PSCRCL
#define PSCRCL

#ifndef PSCRCL_HPP

/* Mode flags */
#define PSCRCL_PREC_FLOAT			0x000	/* Single precision arithmetics */
#define PSCRCL_PREC_DOUBLE			0x001	/* Double precision arithmetics */
#define PSCRCL_NUM_REAL				0x000	/* Real numbers */
#define PSCRCL_NUM_COMPLEX			0x002	/* Complex numbers */

#define PSCRCL_M1_TRIDIAG			0x010	/* M1 is tridiagonal */
#define PSCRCL_M2_TRIDIAG			0x020	/* M2 is tridiagonal */
#define PSCRCL_M3_TRIDIAG			0x040	/* M3 is tridiagonal */

#define PSCRCL_OK			 		 0		/* Everything went OK */
#define PSCRCL_ERROR_ARGS			-1		/* Invalid arguments */
#define PSCRCL_ERROR_PARAMS			-2		/* Invalid parameters */
#define PSCRCL_ERROR_OPENCL 		-3		/* OpenCL related error */
#define PSCRCL_ERROR_UNKNOWN		-4		/* Unknown error */

#define PSCRCL_MAX_N1				99999
#define PSCRCL_MAX_N2				99999
#define PSCRCL_MAX_N3				99999

/* Parameter id:s */
#define PSCRCL_OPT_PARAM_L3_PREFIX							300
#define PSCRCL_OPT_PARAM_L3_D								301
#define PSCRCL_OPT_PARAM_L3_HILODOUBLE						302
#define PSCRCL_OPT_PARAM_L3_SHARED_ISOLATED_ACCESS			303
#define PSCRCL_OPT_PARAM_L3_NEWTON_DIV						304
#define PSCRCL_OPT_PARAM_L3_GEN_GLOBAL_SYS_WG_SIZE			305
#define PSCRCL_OPT_PARAM_L3_GEN_GLOBAL_SYS_WG_PER_SYS		306
#define PSCRCL_OPT_PARAM_L3_A_WG_SIZE						307
#define PSCRCL_OPT_PARAM_L3_BCD_WG_SIZE						308
#define PSCRCL_OPT_PARAM_L3_LOCAL_MEM_SIZE					309
#define PSCRCL_OPT_PARAM_L3_PCR_LIMIT						310
#define PSCRCL_OPT_PARAM_L3_PCR_STEPS						311
#define PSCRCL_OPT_PARAM_L3_PARALLEL_STAGE_A1				312
#define PSCRCL_OPT_PARAM_L3_PARALLEL_STAGE_A2				313

#define PSCRCL_OPT_PARAM_L2_PREFIX							200
#define PSCRCL_OPT_PARAM_L2_D								201
#define PSCRCL_OPT_PARAM_L2_SHARED_ISOLATED_ACCESS			202
#define PSCRCL_OPT_PARAM_L2_NEWTON_DIV						203
#define PSCRCL_OPT_PARAM_L2_STAGE_11_WG_SIZE				204
#define PSCRCL_OPT_PARAM_L2_STAGE_11_WG_PER_VECTOR			205
#define PSCRCL_OPT_PARAM_L2_STAGE_12A_WG_SIZE				206
#define PSCRCL_OPT_PARAM_L2_STAGE_12A_WG_PER_VECTOR			207
#define PSCRCL_OPT_PARAM_L2_STAGE_12C_WG_SIZE				208
#define PSCRCL_OPT_PARAM_L2_STAGE_12C_WG_PER_VECTOR			209
#define PSCRCL_OPT_PARAM_L2_STAGE_Y2A_MAX_SUM_SIZE_EXP		210
#define PSCRCL_OPT_PARAM_L2_STAGE_Y2B_MAX_SUM_SIZE_EXP		211
#define PSCRCL_OPT_PARAM_L2_STAGE_Y2B_WG_SIZE				212
#define PSCRCL_OPT_PARAM_L2_STAGE_Y2B_WG_PER_VECTOR			213
#define PSCRCL_OPT_PARAM_L2_STAGE_21_WG_SIZE				214
#define PSCRCL_OPT_PARAM_L2_STAGE_21_WG_PER_VECTOR			215
#define PSCRCL_OPT_PARAM_L2_STAGE_22A_WG_SIZE				216
#define PSCRCL_OPT_PARAM_L2_STAGE_22A_WG_PER_VECTOR			217
#define PSCRCL_OPT_PARAM_L2_STAGE_22C_WG_SIZE				218
#define PSCRCL_OPT_PARAM_L2_STAGE_22C_WG_PER_VECTOR			219
#define PSCRCL_OPT_PARAM_L2_VECTOR_LOAD_HELPER				220
#define PSCRCL_OPT_PARAM_L2_MATRIX_LOAD_HELPER				221

#define PSCRCL_OPT_PARAM_L1_PREFIX							100
#define PSCRCL_OPT_PARAM_L1_D								101
#define PSCRCL_OPT_PARAM_L1_SHARED_ISOLATED_ACCESS			102
#define PSCRCL_OPT_PARAM_L1_NEWTON_DIV						103
#define PSCRCL_OPT_PARAM_L1_STAGE_11_WG_SIZE				104
#define PSCRCL_OPT_PARAM_L1_STAGE_11_WG_PER_VECTOR			105
#define PSCRCL_OPT_PARAM_L1_STAGE_12A_WG_SIZE				106
#define PSCRCL_OPT_PARAM_L1_STAGE_12A_WG_PER_VECTOR			107
#define PSCRCL_OPT_PARAM_L1_STAGE_12C_WG_SIZE				108
#define PSCRCL_OPT_PARAM_L1_STAGE_12C_WG_PER_VECTOR			109
#define PSCRCL_OPT_PARAM_L1_STAGE_Y2A_MAX_SUM_SIZE_EXP		110
#define PSCRCL_OPT_PARAM_L1_STAGE_Y2B_MAX_SUM_SIZE_EXP		111
#define PSCRCL_OPT_PARAM_L1_STAGE_Y2B_WG_SIZE				112
#define PSCRCL_OPT_PARAM_L1_STAGE_Y2B_WG_PER_VECTOR			113
#define PSCRCL_OPT_PARAM_L1_STAGE_21_WG_SIZE				114
#define PSCRCL_OPT_PARAM_L1_STAGE_21_WG_PER_VECTOR			115
#define PSCRCL_OPT_PARAM_L1_STAGE_22A_WG_SIZE				116
#define PSCRCL_OPT_PARAM_L1_STAGE_22A_WG_PER_VECTOR			117
#define PSCRCL_OPT_PARAM_L1_STAGE_22C_WG_SIZE				118
#define PSCRCL_OPT_PARAM_L1_STAGE_22C_WG_PER_VECTOR			119
#define PSCRCL_OPT_PARAM_L1_VECTOR_LOAD_HELPER				120
#define PSCRCL_OPT_PARAM_L1_MATRIX_LOAD_HELPER				121

#endif

typedef int pscrCL_error_code;
typedef unsigned int pscrCL_mode_flag;
typedef int pscrCL_opt_id;

typedef void* level2_solver;

#endif
